/*
 * ForkFolio — catalogo dati modificabili.
 *
 * Modifica qui ingredienti, ricette, prodotti ricorrenti e categorie della spesa.
 * Mantieni stabili gli id delle ricette e i nomi degli ingredienti già usati nelle
 * ricette, così i riferimenti e la lista della spesa continueranno a risolversi.
 */

(() => {
      const STAPLES = {
        Colazione: [
          "Avena",
          "Cacao",
          "Uova (scorta)",
          "Miele",
          "Marmellata",
          "Pane per colazione",
        ],
        "Snack & Merende": [
          "Banane",
          "Mela",
          "Frutta varia",
          "Burro di arachidi",
          "Barrette per merenda",
          "Dolcetti",
        ],
        Bevande: [
          "Caffè",
          "Acqua naturale",
          "Acqua frizzante",
          "Succo di frutta 100%",
          "Energetiche",
          "Sciroppo alla menta",
        ],
        "Dispensa Base": ["Olio EVO (scorta)", "Sale", "Pepe"],
        Latticini: ["Latte", "Yogurt bianco", "Yogurt da bere"],
        "Pane & Carboidrati": ["Grissini"],
      };

      const INGREDIENTS = {
        "🥩 Carni": {
          "🐔 Pollo": [
            "Petto di pollo",
            "Sovracosce di pollo",
            "Ali di pollo",
            "Pollo intero",
            "Straccetti di pollo",
            "Pollo marinato",
          ],
          "🥩 Manzo": [
            "Bistecca di manzo",
            "Straccetti di manzo",
            "Hamburger di manzo",
            "Carpaccio di manzo",
            "Bresaola",
            "Polpette di manzo",
            "Manzo spezzatino",
            "Tagliata di manzo",
            "Tartare di manzo",
          ],
          "🐖 Maiale": [
            "Lonza di maiale",
            "Filetto di maiale",
            "Prosciutto crudo",
            "Prosciutto cotto",
            "Pancetta/guanciale",
            "Polpette di suino",
            "Speck",
          ],
          "🦃 Tacchino": [
            "Fesa di tacchino",
            "Arrosto di tacchino",
            "Polpette di tacchino",
            "Tacchino alla griglia",
          ],
        },
        "🐟 Pesce": {
          Freschi: [
            "Orata",
            "Branzino",
            "Salmone fresco",
            "Trota salmonata",
            "Merluzzo",
            "Sgombro fresco",
            "Tonno fresco",
            "Calamari",
            "Gamberetti",
            "Vongole sgusciate (surgelate)",
          ],
          Conserve: [
            "Tonno al naturale",
            "Tonno in olio",
            "Sgombro in scatola",
            "Salmone affumicato",
            "Acciughe",
            "Sardine",
            "Polpo precotto",
          ],
        },
        "🥚 Uova & Formaggi": {
          Uova: [
            "Uova strapazzate",
            "Uova sode",
            "Frittata",
            "Uova all'occhio di bue",
            "Uovo alla coque",
            "Frittata al forno",
          ],
          Formaggi: [
            "Ricotta vaccina",
            "Ricotta di pecora",
            "Mozzarella",
            "Mozzarella light",
            "Fiocchi di latte",
            "Primo sale",
            "Feta",
            "Pecorino",
            "Parmigiano/Grana",
            "Scamorza",
            "Sottilette",
          ],
        },
        "🫘 Legumi & Veg.": {
          Legumi: [
            "Ceci",
            "Lenticchie rosse",
            "Lenticchie verdi",
            "Fagioli cannellini",
            "Fagioli borlotti",
            "Fagioli rossi",
            "Edamame",
            "Soia gialla",
            "Piselli",
          ],
          "Proteine vegetali": [
            "Tofu naturale",
            "Tofu affumicato",
            "Tempeh",
            "Seitan",
            "Burger vegetali",
            "Hummus di ceci",
            "Hummus di barbabietola",
          ],
        },
        "🍚 Carboidrati": {
          Pasta: [
            "Spaghetti",
            "Penne",
            "Trofie",
            "Rigatoni",
            "Fusilli",
            "Pasta integrale",
            "Pasta ai legumi",
            "Lasagne",
            "Orecchiette",
            "Tagliatelle",
          ],
          "Riso & Cereali": [
            "Riso basmati",
            "Riso integrale",
            "Riso venere",
            "Riso jasmine",
            "Cous cous",
            "Cous cous integrale",
            "Bulgur",
            "Farro",
            "Orzo",
            "Quinoa",
            "Miglio",
          ],
          "Pane & Altro": [
            "Pane integrale",
            "Pane ai cereali",
            "Pane di segale",
            "Piadina",
            "Piadina integrale",
            "Pita",
            "Wrap",
            "Gnocchi di patate",
            "Polenta",
            "Crackers integrali",
            "Grissini",
            "Fiocchi d'avena",
            "Crostini di pane",
            "Pangrattato",
            "Saikebon",
          ],
          Tuberi: ["Patate", "Patate dolci", "Zucca (autunno)", "Topinambur"],
        },
        "🥦 Verdure": {
          "☀️ Estate": [
            "Zucchine",
            "Melanzane",
            "Peperoni",
            "Peperoncino fresco",
            "Pomodorini ciliegino",
            "Pomodori ramati",
            "Cetrioli",
            "Mais",
          ],
          "🍂 Autunno-Inverno": [
            "Spinaci",
            "Finocchi",
            "Broccoli",
            "Cavolfiore",
            "Cavolo verza",
            "Cavolo nero",
            "Bietole",
            "Radicchio",
            "Cavolo cappuccio",
            "Porri",
          ],
          "🌿 Primavera": [
            "Asparagi",
            "Fagiolini",
            "Piselli freschi",
            "Carciofi",
            "Fave fresche",
          ],
          "🔄 Tutto l'anno": [
            "Carote",
            "Cipolla rossa",
            "Cipolla bianca",
            "Cipolla di Tropea",
            "Sedano",
            "Barbabietola",
            "Funghi champignon",
            "Funghi porcini",
            "Avocado",
            "Rucola",
            "Lattuga/misticanza",
            "Songino",
            "Mix verdure surgelate",
          ],
        },
        "🥄 Salse": {
          Basi: [
            "Olio EVO",
            "Salsa di pomodoro",
            "Passata di pomodoro",
            "Pesto basilico",
            "Pesto rucola",
            "Pesto pistacchio",
            "Crema di peperoni",
          ],
          "Salse internazionali": [
            "Salsa di soia",
            "Salsa tahina",
            "Yogurt greco",
            "Yogurt magro",
            "Tzatziki",
            "Guacamole",
            "Hummus",
            "Glassa balsamica",
            "Aceto balsamico",
            "Aceto di mele",
            "Maionese light",
            "Senape Dijon",
            "Senape al miele",
            "Panna",
          ],
          "Agrumi & Freschezza": [
            "Limone",
            "Lime",
            "Arancia",
            "Succo di limone",
          ],
        },
        "🧄 Aromi & Topping": {
          "Aromi freschi": [
            "Aglio",
            "Prezzemolo",
            "Basilico",
            "Menta",
            "Erba cipollina",
            "Rosmarino",
            "Timo",
            "Salvia",
            "Zenzero fresco",
            "Peperoncino fresco",
          ],
          "Spezie secche": [
            "Origano",
            "Paprika dolce",
            "Paprika affumicata",
            "Curry",
            "Cumino",
            "Curcuma",
            "Peperoncino secco",
            "Cannella",
            "Pepe",
            "Noce moscata",
            "Za'atar",
          ],
          "Topping & Frutta secca": [
            "Olive nere",
            "Olive verdi",
            "Olive taggiasche",
            "Capperi",
            "Pomodori secchi",
            "Parmigiano grattugiato",
            "Semi di sesamo",
            "Semi di zucca",
            "Semi di girasole",
            "Semi di lino",
            "Noci",
            "Mandorle",
            "Pistacchi",
            "Anacardi",
            "Pinoli",
          ],
        },
      };

      const RECIPES = [
        // 🍝 Pasta & Cereali
        {
          id: 1,
          cat: "🍝 Pasta & Cereali",
          name: "Trofie zucchina, cipolla, panna e pancetta",
          tags: ["pasta", "pancetta", "cremosa"],
          ing: {
            proteine: ["Pancetta/guanciale"],
            carb: ["Trofie"],
            verd: ["Zucchine", "Cipolla bianca"],
            salse: ["Panna", "Olio EVO"],
          },
        },
        {
          id: 2,
          cat: "🍝 Pasta & Cereali",
          name: "Spaghetti al pomodoro, olive e acciughe",
          tags: ["pasta", "pesce", "mediterraneo"],
          ing: {
            proteine: ["Acciughe"],
            carb: ["Spaghetti"],
            verd: ["Pomodorini ciliegino"],
            aromi: ["Olive nere", "Origano", "Aglio"],
          },
        },
        {
          id: 3,
          cat: "🍝 Pasta & Cereali",
          name: "Pasta fredda tonno, mais e pomodorini",
          tags: ["pasta fredda", "tonno", "estate"],
          ing: {
            proteine: ["Tonno al naturale"],
            carb: ["Penne"],
            verd: ["Pomodorini ciliegino", "Mais"],
            aromi: ["Olive nere", "Basilico"],
          },
        },
        {
          id: 4,
          cat: "🍝 Pasta & Cereali",
          name: "Spaghetti aglio, olio, acciughe e pangrattato croccante",
          tags: ["pasta", "veloce", "acciughe"],
          ing: {
            proteine: ["Acciughe"],
            carb: ["Spaghetti"],
            aromi: ["Aglio", "Peperoncino fresco", "Prezzemolo"],
          },
        },
        {
          id: 5,
          cat: "🍝 Pasta & Cereali",
          name: "Orzo freddo con salmone affumicato, avocado e cetriolo",
          tags: ["orzo", "salmone", "fresco"],
          ing: {
            proteine: ["Salmone affumicato"],
            carb: ["Orzo"],
            verd: ["Avocado", "Cetrioli"],
            salse: ["Limone", "Olio EVO"],
          },
        },
        {
          id: 6,
          cat: "🍝 Pasta & Cereali",
          name: "Farro con verdure grigliate, feta e menta",
          tags: ["farro", "feta", "estate"],
          ing: {
            proteine: ["Feta"],
            carb: ["Farro"],
            verd: ["Zucchine", "Peperoni", "Cipolla rossa"],
            salse: ["Olio EVO", "Aceto balsamico"],
            aromi: ["Menta"],
          },
        },
        {
          id: 7,
          cat: "🍝 Pasta & Cereali",
          name: "Quinoa con gamberetti, avocado e lime",
          tags: ["quinoa", "gamberetti", "bowl"],
          ing: {
            proteine: ["Gamberetti"],
            carb: ["Quinoa"],
            verd: ["Avocado", "Pomodorini ciliegino"],
            salse: ["Lime", "Olio EVO"],
            aromi: ["Erba cipollina", "Peperoncino fresco"],
          },
        },
        // 🌾 Cous Cous & Riso
        {
          id: 8,
          cat: "🌾 Cous Cous & Riso",
          name: "Cous cous mozzarella, pomodorini, basilico e acciughe",
          tags: ["cous cous", "mozzarella", "estate"],
          ing: {
            proteine: ["Mozzarella", "Acciughe"],
            carb: ["Cous cous"],
            verd: ["Pomodorini ciliegino"],
            aromi: ["Basilico"],
          },
        },
        {
          id: 9,
          cat: "🌾 Cous Cous & Riso",
          name: "Cous cous zucchine, trota salmonata e acciughe",
          tags: ["cous cous", "pesce"],
          ing: {
            proteine: ["Trota salmonata", "Acciughe"],
            carb: ["Cous cous"],
            verd: ["Zucchine"],
            salse: ["Olio EVO", "Limone"],
          },
        },
        {
          id: 10,
          cat: "🌾 Cous Cous & Riso",
          name: "Cous cous tonno, olive nere, pomodorini e melanzane",
          tags: ["cous cous", "tonno", "estate"],
          ing: {
            proteine: ["Tonno al naturale", "Acciughe"],
            carb: ["Cous cous"],
            verd: ["Pomodorini ciliegino", "Melanzane"],
            aromi: ["Olive nere", "Origano", "Peperoncino secco"],
          },
        },
        {
          id: 11,
          cat: "🌾 Cous Cous & Riso",
          name: "Cous cous pollo aromatizzato, carote e zucchine",
          tags: ["cous cous", "pollo", "forno"],
          ing: {
            proteine: ["Sovracosce di pollo"],
            carb: ["Cous cous"],
            verd: ["Carote", "Cipolla rossa", "Zucchine"],
            aromi: ["Paprika dolce", "Rosmarino", "Olio EVO"],
          },
        },
        {
          id: 12,
          cat: "🌾 Cous Cous & Riso",
          name: "Riso basmati, straccetti di manzo, broccolo e salsa di soia",
          tags: ["riso", "manzo", "asiatico"],
          ing: {
            proteine: ["Straccetti di manzo"],
            carb: ["Riso basmati"],
            verd: ["Broccoli", "Carote", "Cipolla bianca"],
            salse: ["Salsa di soia", "Olio EVO"],
          },
        },
        {
          id: 13,
          cat: "🌾 Cous Cous & Riso",
          name: "Riso venere con salmone in padella, zucchine e limone",
          tags: ["riso venere", "salmone", "elegante"],
          ing: {
            proteine: ["Salmone fresco"],
            carb: ["Riso venere"],
            verd: ["Zucchine"],
            salse: ["Limone", "Olio EVO"],
            aromi: ["Erba cipollina"],
          },
        },
        {
          id: 14,
          cat: "🌾 Cous Cous & Riso",
          name: "Poke bowl: riso, salmone, avocado ed edamame",
          tags: ["poke", "salmone", "bowl"],
          ing: {
            proteine: ["Salmone fresco", "Edamame"],
            carb: ["Riso basmati"],
            verd: ["Avocado", "Carote", "Cetrioli"],
            salse: ["Salsa di soia"],
            aromi: ["Semi di sesamo", "Zenzero fresco"],
          },
        },
        {
          id: 15,
          cat: "🌾 Cous Cous & Riso",
          name: "Bulgur con pollo alla curcuma, spinaci e yogurt",
          tags: ["bulgur", "pollo", "speziato"],
          ing: {
            proteine: ["Petto di pollo"],
            carb: ["Bulgur"],
            verd: ["Spinaci"],
            salse: ["Yogurt greco"],
            aromi: ["Curcuma", "Cumino", "Limone"],
          },
        },
        // 🥩 Proteine Protagoniste
        {
          id: 16,
          cat: "🥩 Proteine Protagoniste",
          name: "Petto di pollo alla griglia con riso e finocchio",
          tags: ["pollo", "riso", "leggero"],
          ing: {
            proteine: ["Petto di pollo"],
            carb: ["Riso basmati"],
            verd: ["Finocchi"],
            salse: ["Olio EVO", "Limone"],
          },
        },
        {
          id: 17,
          cat: "🥩 Proteine Protagoniste",
          name: "Cheeseburger artigianale con insalata mista",
          tags: ["manzo", "burger", "casual"],
          ing: {
            proteine: ["Hamburger di manzo", "Mozzarella"],
            carb: ["Pane ai cereali"],
            verd: ["Lattuga/misticanza", "Pomodori ramati"],
            salse: ["Senape Dijon", "Maionese light"],
          },
        },
        {
          id: 18,
          cat: "🥩 Proteine Protagoniste",
          name: "Wrap sovracoscia di pollo, cipolla, yogurt e curry",
          tags: ["wrap", "pollo", "fusion"],
          ing: {
            proteine: ["Sovracosce di pollo"],
            carb: ["Wrap"],
            verd: ["Cipolla rossa", "Peperoncino fresco", "Lattuga/misticanza"],
            salse: ["Yogurt greco"],
            aromi: ["Curry"],
          },
        },
        {
          id: 19,
          cat: "🥩 Proteine Protagoniste",
          name: "Orata al cartoccio con pomodorini, olive e capperi",
          tags: ["pesce", "forno", "mediterraneo"],
          ing: {
            proteine: ["Orata"],
            verd: ["Pomodorini ciliegino"],
            aromi: ["Olive nere", "Capperi", "Aglio", "Prezzemolo", "Olio EVO"],
          },
        },
        {
          id: 20,
          cat: "🥩 Proteine Protagoniste",
          name: "Salmone in padella con quinoa e spinaci saltati",
          tags: ["salmone", "quinoa", "fit"],
          ing: {
            proteine: ["Salmone fresco"],
            carb: ["Quinoa"],
            verd: ["Spinaci"],
            salse: ["Limone", "Olio EVO"],
            aromi: ["Zenzero fresco"],
          },
        },
        {
          id: 21,
          cat: "🥩 Proteine Protagoniste",
          name: "Tonno scottato, insalata di avocado e lime",
          tags: ["tonno", "avocado", "fresco"],
          ing: {
            proteine: ["Tonno fresco"],
            verd: ["Avocado", "Pomodorini ciliegino", "Rucola"],
            salse: ["Lime"],
            aromi: ["Semi di sesamo"],
          },
        },
        {
          id: 22,
          cat: "🥩 Proteine Protagoniste",
          name: "Tagliata di manzo su rucola, parmigiano e balsamico",
          tags: ["manzo", "rucola", "elegante"],
          ing: {
            proteine: ["Tagliata di manzo"],
            verd: ["Rucola"],
            aromi: ["Parmigiano/Grana", "Pomodori secchi"],
            salse: ["Glassa balsamica", "Olio EVO"],
          },
        },
        {
          id: 23,
          cat: "🥩 Proteine Protagoniste",
          name: "Lonza di maiale al vino bianco con patate al forno",
          tags: ["maiale", "patate", "forno"],
          ing: {
            proteine: ["Lonza di maiale"],
            carb: ["Patate"],
            aromi: ["Rosmarino", "Aglio", "Olio EVO"],
          },
        },
        {
          id: 24,
          cat: "🥩 Proteine Protagoniste",
          name: "Branzino al sale con patate dolci e asparagi",
          tags: ["pesce", "forno", "dietetico"],
          ing: {
            proteine: ["Branzino"],
            carb: ["Patate dolci"],
            verd: ["Asparagi"],
            salse: ["Limone", "Olio EVO"],
          },
        },
        // 🥚 Uova & Formaggi
        {
          id: 25,
          cat: "🥚 Uova & Formaggi",
          name: "Uova strapazzate con zucchine trifolate e riso",
          tags: ["uova", "zucchine", "quick"],
          ing: {
            proteine: ["Uova strapazzate"],
            carb: ["Riso basmati"],
            verd: ["Zucchine"],
            salse: ["Olio EVO"],
            aromi: ["Erba cipollina"],
          },
        },
        {
          id: 26,
          cat: "🥚 Uova & Formaggi",
          name: "Frittata al forno con spinaci e feta",
          tags: ["uova", "feta", "forno"],
          ing: {
            proteine: ["Frittata al forno", "Feta"],
            verd: ["Spinaci", "Cipolla bianca"],
            salse: ["Olio EVO"],
            aromi: ["Origano"],
          },
        },
        {
          id: 27,
          cat: "🥚 Uova & Formaggi",
          name: "Panino ricotta, tacchino, rucola e glassa balsamica",
          tags: ["panino", "tacchino", "ricotta"],
          ing: {
            proteine: [
              "Fesa di tacchino",
              "Ricotta vaccina",
              "Uova strapazzate",
            ],
            carb: ["Pane ai cereali"],
            verd: ["Rucola"],
            salse: ["Glassa balsamica"],
          },
        },
        {
          id: 28,
          cat: "🥚 Uova & Formaggi",
          name: "Frittata di verdure al forno con feta e erbe",
          tags: ["uova", "verdure", "light"],
          ing: {
            proteine: ["Frittata al forno", "Feta"],
            verd: ["Peperoni", "Zucchine", "Cipolla rossa"],
            aromi: ["Origano", "Timo", "Olio EVO"],
          },
        },
        // 🫘 Legumi & Verdure
        {
          id: 29,
          cat: "🫘 Legumi & Verdure",
          name: "Hummus di ceci con pane integrale e melanzane grigliate",
          tags: ["legumi", "vegan", "pane"],
          ing: {
            proteine: ["Ceci", "Hummus di ceci"],
            carb: ["Pane integrale"],
            verd: ["Melanzane"],
            salse: ["Olio EVO", "Limone"],
            aromi: ["Paprika dolce"],
          },
        },
        {
          id: 30,
          cat: "🫘 Legumi & Verdure",
          name: "Lenticchie al pomodoro con cipolla e acciughe",
          tags: ["legumi", "umido", "rustico"],
          ing: {
            proteine: ["Lenticchie verdi", "Acciughe"],
            carb: ["Riso basmati"],
            verd: ["Cipolla rossa"],
            salse: ["Salsa di pomodoro", "Olio EVO"],
          },
        },
        {
          id: 31,
          cat: "🫘 Legumi & Verdure",
          name: "Bowl di ceci al curry, riso basmati e spinaci",
          tags: ["legumi", "curry", "bowl"],
          ing: {
            proteine: ["Ceci"],
            carb: ["Riso basmati"],
            verd: ["Spinaci", "Cipolla bianca"],
            salse: ["Salsa di pomodoro"],
            aromi: ["Curry", "Curcuma", "Zenzero fresco"],
          },
        },
        {
          id: 32,
          cat: "🫘 Legumi & Verdure",
          name: "Zuppa di fagioli cannellini con rosmarino e pane tostato",
          tags: ["legumi", "zuppa", "invernale"],
          ing: {
            proteine: ["Fagioli cannellini"],
            carb: ["Pane ai cereali"],
            verd: ["Cipolla bianca", "Sedano", "Carote"],
            aromi: ["Rosmarino", "Aglio", "Olio EVO"],
          },
        },
        {
          id: 33,
          cat: "🫘 Legumi & Verdure",
          name: "Lenticchie rosse con cocco e zenzero su riso integrale",
          tags: ["legumi", "fusion", "vegan"],
          ing: {
            proteine: ["Lenticchie rosse"],
            carb: ["Riso integrale"],
            verd: ["Cipolla bianca"],
            aromi: ["Zenzero fresco", "Curcuma", "Curry"],
          },
        },
        // 🥗 Bowl & Insalate
        {
          id: 34,
          cat: "🥗 Bowl & Insalate",
          name: "Bowl mediterranea: bulgur, feta, olive e pomodorini",
          tags: ["bulgur", "feta", "estate"],
          ing: {
            proteine: ["Feta"],
            carb: ["Bulgur"],
            verd: ["Pomodorini ciliegino", "Cetrioli", "Cipolla rossa"],
            aromi: ["Olive nere", "Menta", "Olio EVO"],
          },
        },
        {
          id: 35,
          cat: "🥗 Bowl & Insalate",
          name: "Insalata tiepida di lenticchie, radicchio e noci",
          tags: ["legumi", "insalata", "autunno"],
          ing: {
            proteine: ["Lenticchie verdi"],
            verd: ["Radicchio", "Cipolla rossa"],
            salse: ["Glassa balsamica", "Olio EVO"],
            aromi: ["Noci"],
          },
        },
        {
          id: 36,
          cat: "🥗 Bowl & Insalate",
          name: "Insalata di sgombro, fagiolini e uova sode",
          tags: ["pesce", "uova", "estate"],
          ing: {
            proteine: ["Sgombro in scatola", "Uova sode"],
            verd: ["Fagiolini", "Pomodorini ciliegino"],
            salse: ["Olio EVO", "Aceto di mele"],
          },
        },
        {
          id: 37,
          cat: "🥗 Bowl & Insalate",
          name: "Caesar salad con petto di pollo e parmigiano",
          tags: ["pollo", "insalata", "classica"],
          ing: {
            proteine: ["Petto di pollo"],
            verd: ["Lattuga/misticanza"],
            aromi: ["Parmigiano grattugiato", "Aglio"],
            salse: ["Maionese light", "Limone"],
          },
        },
        // 🍝 Pasta & Cereali — nuovi primi rapidi e mediterranei
        {
          id: 38,
          cat: "🍝 Pasta & Cereali",
          name: "Spaghetti alle vongole sgusciate, zucchine e prezzemolo",
          tags: ["pasta", "pesce", "veloce", "mediterraneo"],
          ing: {
            proteine: ["Vongole sgusciate (surgelate)"],
            carb: ["Spaghetti"],
            verd: ["Zucchine"],
            aromi: ["Aglio", "Prezzemolo", "Peperoncino fresco"],
          },
        },
        {
          id: 39,
          cat: "🍝 Pasta & Cereali",
          name: "Penne cremose al salmone, spinaci e limone",
          tags: ["pasta", "salmone", "high-protein", "veloce"],
          ing: {
            proteine: ["Salmone fresco"],
            carb: ["Penne"],
            verd: ["Spinaci"],
            salse: ["Panna", "Limone"],
            aromi: ["Erba cipollina"],
          },
        },
        {
          id: 40,
          cat: "🍝 Pasta & Cereali",
          name: "Trofie con gamberetti, pesto e pomodorini",
          tags: ["pasta", "gamberetti", "estate", "veloce"],
          ing: {
            proteine: ["Gamberetti"],
            carb: ["Trofie"],
            verd: ["Pomodorini ciliegino"],
            salse: ["Pesto basilico"],
            aromi: ["Basilico"],
          },
        },
        {
          id: 41,
          cat: "🍝 Pasta & Cereali",
          name: "Rigatoni con straccetti di manzo, pomodoro e rucola",
          tags: ["pasta", "manzo", "high-protein", "padella"],
          ing: {
            proteine: ["Straccetti di manzo"],
            carb: ["Rigatoni"],
            verd: ["Pomodorini ciliegino", "Rucola"],
            salse: ["Salsa di pomodoro", "Olio EVO"],
            aromi: ["Aglio"],
          },
        },
        {
          id: 42,
          cat: "🍝 Pasta & Cereali",
          name: "Fusilli con pollo, pesto di rucola e pomodorini",
          tags: ["pasta", "pollo", "high-protein", "veloce"],
          ing: {
            proteine: ["Petto di pollo"],
            carb: ["Fusilli"],
            verd: ["Pomodorini ciliegino"],
            salse: ["Pesto rucola"],
            aromi: ["Parmigiano grattugiato"],
          },
        },
        {
          id: 43,
          cat: "🍝 Pasta & Cereali",
          name: "Tagliatelle speck, porri e panna",
          tags: ["pasta", "speck", "cremosa", "sfiziosa"],
          ing: {
            proteine: ["Speck"],
            carb: ["Tagliatelle"],
            verd: ["Porri"],
            salse: ["Panna"],
            aromi: ["Pepe"],
          },
        },
        {
          id: 44,
          cat: "🍝 Pasta & Cereali",
          name: "Orecchiette con broccoli, acciughe e pangrattato",
          tags: ["pasta", "pesce", "mediterraneo", "veloce"],
          ing: {
            proteine: ["Acciughe"],
            carb: ["Orecchiette", "Pangrattato"],
            verd: ["Broccoli"],
            aromi: ["Aglio", "Peperoncino secco"],
          },
        },
        {
          id: 45,
          cat: "🍝 Pasta & Cereali",
          name: "Spaghetti tonno, capperi, limone e olive",
          tags: ["pasta", "tonno", "dispensa", "veloce"],
          ing: {
            proteine: ["Tonno al naturale"],
            carb: ["Spaghetti"],
            salse: ["Limone", "Olio EVO"],
            aromi: ["Capperi", "Olive taggiasche", "Prezzemolo"],
          },
        },
        // 🌾 Cous Cous & Riso — bowl calde e piatti unici
        {
          id: 46,
          cat: "🌾 Cous Cous & Riso",
          name: "Riso basmati con manzo, peperoni e paprika affumicata",
          tags: ["riso", "manzo", "high-protein", "padella"],
          ing: {
            proteine: ["Straccetti di manzo"],
            carb: ["Riso basmati"],
            verd: ["Peperoni", "Cipolla rossa"],
            salse: ["Olio EVO"],
            aromi: ["Paprika affumicata"],
          },
        },
        {
          id: 47,
          cat: "🌾 Cous Cous & Riso",
          name: "Riso jasmine con gamberetti, zucchine e curry",
          tags: ["riso", "gamberetti", "fusion", "veloce"],
          ing: {
            proteine: ["Gamberetti"],
            carb: ["Riso jasmine"],
            verd: ["Zucchine", "Cipolla bianca"],
            salse: ["Yogurt greco"],
            aromi: ["Curry", "Zenzero fresco"],
          },
        },
        {
          id: 48,
          cat: "🌾 Cous Cous & Riso",
          name: "Cous cous con sgombro, feta, zucchine e menta",
          tags: ["cous cous", "sgombro", "estate", "veloce"],
          ing: {
            proteine: ["Sgombro in scatola", "Feta"],
            carb: ["Cous cous"],
            verd: ["Zucchine"],
            salse: ["Limone", "Olio EVO"],
            aromi: ["Menta"],
          },
        },
        {
          id: 49,
          cat: "🌾 Cous Cous & Riso",
          name: "Riso basmati con tacchino, spinaci e salsa di soia",
          tags: ["riso", "tacchino", "high-protein", "veloce"],
          ing: {
            proteine: ["Fesa di tacchino"],
            carb: ["Riso basmati"],
            verd: ["Spinaci", "Carote"],
            salse: ["Salsa di soia"],
            aromi: ["Zenzero fresco", "Semi di sesamo"],
          },
        },
        {
          id: 50,
          cat: "🌾 Cous Cous & Riso",
          name: "Orzo con salmone affumicato, broccoli e yogurt al limone",
          tags: ["orzo", "salmone", "high-protein", "veloce"],
          ing: {
            proteine: ["Salmone affumicato"],
            carb: ["Orzo"],
            verd: ["Broccoli"],
            salse: ["Yogurt greco", "Limone"],
            aromi: ["Erba cipollina"],
          },
        },
        // 🥩 Proteine Protagoniste — carne e pesce per cene quotidiane o weekend
        {
          id: 51,
          cat: "🥩 Proteine Protagoniste",
          name: "Straccetti di manzo con rucola, patate e balsamico",
          tags: ["manzo", "high-protein", "veloce", "padella"],
          ing: {
            proteine: ["Straccetti di manzo"],
            carb: ["Patate"],
            verd: ["Rucola"],
            salse: ["Glassa balsamica", "Olio EVO"],
            aromi: ["Rosmarino"],
          },
        },
        {
          id: 52,
          cat: "🥩 Proteine Protagoniste",
          name: "Bistecca di manzo con funghi e patate dolci",
          tags: ["manzo", "high-protein", "cena", "padella"],
          ing: {
            proteine: ["Bistecca di manzo"],
            carb: ["Patate dolci"],
            verd: ["Funghi champignon"],
            salse: ["Olio EVO"],
            aromi: ["Rosmarino", "Aglio"],
          },
        },
        {
          id: 53,
          cat: "🥩 Proteine Protagoniste",
          name: "Tartare di manzo con avocado, songino e crostini",
          tags: ["tartare", "manzo", "high-protein", "weekend"],
          ing: {
            proteine: ["Tartare di manzo"],
            carb: ["Crostini di pane"],
            verd: ["Avocado", "Songino"],
            salse: ["Limone"],
            aromi: ["Pepe", "Capperi"],
          },
        },
        {
          id: 54,
          cat: "🥩 Proteine Protagoniste",
          name: "Carpaccio di manzo, rucola, grana e limone",
          tags: ["carpaccio", "manzo", "high-protein", "veloce"],
          ing: {
            proteine: ["Carpaccio di manzo", "Parmigiano/Grana"],
            verd: ["Rucola"],
            salse: ["Limone", "Olio EVO"],
            aromi: ["Pepe"],
          },
        },
        {
          id: 55,
          cat: "🥩 Proteine Protagoniste",
          name: "Hamburger di manzo con cipolla, scamorza e patate",
          tags: ["burger", "manzo", "high-protein", "sfiziosa"],
          ing: {
            proteine: ["Hamburger di manzo", "Scamorza"],
            carb: ["Patate"],
            verd: ["Cipolla rossa"],
            salse: ["Senape Dijon"],
          },
        },
        {
          id: 56,
          cat: "🥩 Proteine Protagoniste",
          name: "Polpette di manzo al pomodoro con cous cous",
          tags: ["polpette", "manzo", "high-protein", "mediterraneo"],
          ing: {
            proteine: ["Polpette di manzo"],
            carb: ["Cous cous"],
            verd: ["Cipolla bianca"],
            salse: ["Salsa di pomodoro"],
            aromi: ["Basilico", "Origano"],
          },
        },
        {
          id: 57,
          cat: "🥩 Proteine Protagoniste",
          name: "Filetto di maiale alla paprika con carote e spinaci",
          tags: ["maiale", "high-protein", "veloce", "padella"],
          ing: {
            proteine: ["Filetto di maiale"],
            verd: ["Carote", "Spinaci"],
            salse: ["Olio EVO"],
            aromi: ["Paprika dolce", "Aglio"],
          },
        },
        {
          id: 58,
          cat: "🥩 Proteine Protagoniste",
          name: "Lonza alla senape con broccoli e riso basmati",
          tags: ["maiale", "high-protein", "cena", "veloce"],
          ing: {
            proteine: ["Lonza di maiale"],
            carb: ["Riso basmati"],
            verd: ["Broccoli"],
            salse: ["Senape Dijon", "Olio EVO"],
          },
        },
        {
          id: 59,
          cat: "🥩 Proteine Protagoniste",
          name: "Sovracosce al curry con peperoni e riso",
          tags: ["pollo", "high-protein", "fusion", "padella"],
          ing: {
            proteine: ["Sovracosce di pollo"],
            carb: ["Riso basmati"],
            verd: ["Peperoni", "Cipolla rossa"],
            salse: ["Yogurt greco"],
            aromi: ["Curry", "Curcuma"],
          },
        },
        {
          id: 60,
          cat: "🥩 Proteine Protagoniste",
          name: "Merluzzo in padella con pomodorini, olive e patate",
          tags: ["pesce", "merluzzo", "high-protein", "veloce"],
          ing: {
            proteine: ["Merluzzo"],
            carb: ["Patate"],
            verd: ["Pomodorini ciliegino"],
            salse: ["Olio EVO"],
            aromi: ["Olive nere", "Capperi", "Prezzemolo"],
          },
        },
        // 🥚 Uova & Formaggi — opzioni veloci e complete
        {
          id: 61,
          cat: "🥚 Uova & Formaggi",
          name: "Uova all'occhio di bue, spinaci e patate saltate",
          tags: ["uova", "high-protein", "veloce", "padella"],
          ing: {
            proteine: ["Uova all'occhio di bue"],
            carb: ["Patate"],
            verd: ["Spinaci"],
            salse: ["Olio EVO"],
            aromi: ["Pepe"],
          },
        },
        {
          id: 62,
          cat: "🥚 Uova & Formaggi",
          name: "Piadina speck, mozzarella e rucola",
          tags: ["piadina", "speck", "veloce", "sfiziosa"],
          ing: {
            proteine: ["Speck", "Mozzarella"],
            carb: ["Piadina"],
            verd: ["Rucola"],
          },
        },
        {
          id: 63,
          cat: "🥚 Uova & Formaggi",
          name: "Panino con fiocchi di latte, pomodorini e basilico",
          tags: ["panino", "latticini", "high-protein", "veloce"],
          ing: {
            proteine: ["Fiocchi di latte"],
            carb: ["Pane ai cereali"],
            verd: ["Pomodorini ciliegino"],
            salse: ["Olio EVO"],
            aromi: ["Basilico"],
          },
        },
        // 🫘 Legumi & Verdure — varietà vegetale pratica
        {
          id: 64,
          cat: "🫘 Legumi & Verdure",
          name: "Tempeh al curry con quinoa e verdure",
          tags: ["tempeh", "vegetariano", "high-protein", "fusion"],
          ing: {
            proteine: ["Tempeh"],
            carb: ["Quinoa"],
            verd: ["Zucchine", "Carote"],
            salse: ["Salsa di soia"],
            aromi: ["Curry", "Zenzero fresco"],
          },
        },
        {
          id: 65,
          cat: "🫘 Legumi & Verdure",
          name: "Cannellini, tonno, cipolla rossa e pomodorini",
          tags: ["legumi", "tonno", "high-protein", "estate"],
          ing: {
            proteine: ["Fagioli cannellini", "Tonno al naturale"],
            carb: ["Crostini di pane"],
            verd: ["Cipolla rossa", "Pomodorini ciliegino"],
            salse: ["Olio EVO", "Aceto di mele"],
            aromi: ["Prezzemolo"],
          },
        },
        // ⚡ Cene Veloci — piatti unici per i giorni feriali
        {
          id: 66,
          cat: "⚡ Cene Veloci",
          name: "Wrap con salmone affumicato, avocado e yogurt",
          tags: ["wrap", "salmone", "high-protein", "veloce"],
          ing: {
            proteine: ["Salmone affumicato"],
            carb: ["Wrap"],
            verd: ["Avocado", "Rucola"],
            salse: ["Yogurt greco", "Limone"],
          },
        },
        {
          id: 67,
          cat: "⚡ Cene Veloci",
          name: "Piadina pollo, zucchine grigliate e scamorza",
          tags: ["piadina", "pollo", "high-protein", "veloce"],
          ing: {
            proteine: ["Petto di pollo", "Scamorza"],
            carb: ["Piadina"],
            verd: ["Zucchine"],
            salse: ["Olio EVO"],
            aromi: ["Origano"],
          },
        },
        {
          id: 68,
          cat: "⚡ Cene Veloci",
          name: "Panino bresaola, ricotta e rucola",
          tags: ["panino", "bresaola", "high-protein", "veloce"],
          ing: {
            proteine: ["Bresaola", "Ricotta vaccina"],
            carb: ["Pane ai cereali"],
            verd: ["Rucola"],
            salse: ["Glassa balsamica"],
          },
        },
        {
          id: 69,
          cat: "⚡ Cene Veloci",
          name: "Saikebon con gamberetti, edamame e salsa di soia",
          tags: ["noodles", "gamberetti", "high-protein", "dispensa"],
          ing: {
            proteine: ["Gamberetti", "Edamame"],
            carb: ["Saikebon"],
            verd: ["Carote"],
            salse: ["Salsa di soia"],
            aromi: ["Semi di sesamo"],
          },
        },
        {
          id: 70,
          cat: "⚡ Cene Veloci",
          name: "Bowl di tonno fresco, riso basmati e avocado",
          tags: ["bowl", "tonno", "high-protein", "veloce"],
          ing: {
            proteine: ["Tonno fresco"],
            carb: ["Riso basmati"],
            verd: ["Avocado", "Cetrioli"],
            salse: ["Salsa di soia", "Lime"],
            aromi: ["Semi di sesamo"],
          },
        },
      ];

      const SHOP_CATS = {
        "🥩 Carni": [
          "Petto di pollo",
          "Sovracosce di pollo",
          "Ali di pollo",
          "Pollo intero",
          "Straccetti di pollo",
          "Pollo marinato",
          "Fesa di tacchino",
          "Arrosto di tacchino",
          "Polpette di tacchino",
          "Tacchino alla griglia",
          "Bistecca di manzo",
          "Straccetti di manzo",
          "Hamburger di manzo",
          "Carpaccio di manzo",
          "Bresaola",
          "Polpette di manzo",
          "Manzo spezzatino",
          "Tagliata di manzo",
          "Tartare di manzo",
          "Lonza di maiale",
          "Filetto di maiale",
          "Prosciutto crudo",
          "Prosciutto cotto",
          "Pancetta/guanciale",
          "Polpette di suino",
          "Speck",
        ],
        "🐟 Pesce": [
          "Orata",
          "Branzino",
          "Salmone fresco",
          "Trota salmonata",
          "Merluzzo",
          "Sgombro fresco",
          "Tonno fresco",
          "Calamari",
          "Gamberetti",
          "Vongole sgusciate (surgelate)",
          "Tonno al naturale",
          "Tonno in olio",
          "Sgombro in scatola",
          "Salmone affumicato",
          "Acciughe",
          "Sardine",
          "Polpo precotto",
        ],
        "🥚 Uova & Latticini": [
          "Uova strapazzate",
          "Uova sode",
          "Uova all'occhio di bue",
          "Frittata",
          "Frittata al forno",
          "Ricotta vaccina",
          "Ricotta di pecora",
          "Mozzarella",
          "Mozzarella light",
          "Fiocchi di latte",
          "Primo sale",
          "Feta",
          "Pecorino",
          "Parmigiano/Grana",
          "Scamorza",
          "Parmigiano grattugiato",
          "Sottilette",
        ],
        "🫘 Legumi": [
          "Ceci",
          "Lenticchie rosse",
          "Lenticchie verdi",
          "Fagioli cannellini",
          "Fagioli borlotti",
          "Fagioli rossi",
          "Edamame",
          "Soia gialla",
          "Piselli",
          "Tofu naturale",
          "Tofu affumicato",
          "Tempeh",
          "Hummus di ceci",
          "Hummus di barbabietola",
        ],
        "🍚 Carboidrati": [
          "Spaghetti",
          "Penne",
          "Trofie",
          "Rigatoni",
          "Fusilli",
          "Pasta integrale",
          "Pasta ai legumi",
          "Orecchiette",
          "Tagliatelle",
          "Riso basmati",
          "Riso integrale",
          "Riso venere",
          "Riso jasmine",
          "Cous cous",
          "Bulgur",
          "Farro",
          "Orzo",
          "Quinoa",
          "Miglio",
          "Pane integrale",
          "Pane ai cereali",
          "Piadina",
          "Pita",
          "Wrap",
          "Gnocchi di patate",
          "Crackers integrali",
          "Crostini di pane",
          "Pangrattato",
          "Saikebon",
        ],
        "🥦 Frutta & Verdura": [
          "Zucchine",
          "Melanzane",
          "Peperoni",
          "Peperoncino fresco",
          "Pomodorini ciliegino",
          "Pomodori ramati",
          "Cetrioli",
          "Mais",
          "Spinaci",
          "Finocchi",
          "Broccoli",
          "Cavolfiore",
          "Cavolo verza",
          "Bietole",
          "Radicchio",
          "Asparagi",
          "Fagiolini",
          "Carote",
          "Cipolla rossa",
          "Cipolla bianca",
          "Sedano",
          "Barbabietola",
          "Funghi champignon",
          "Avocado",
          "Rucola",
          "Lattuga/misticanza",
          "Songino",
          "Patate",
          "Patate dolci",
          "Porri",
        ],
        "🥄 Salse & Condimenti": [
          "Olio EVO",
          "Salsa di pomodoro",
          "Passata di pomodoro",
          "Pesto basilico",
          "Pesto rucola",
          "Salsa di soia",
          "Salsa tahina",
          "Yogurt greco",
          "Tzatziki",
          "Hummus",
          "Glassa balsamica",
          "Aceto balsamico",
          "Aceto di mele",
          "Maionese light",
          "Senape Dijon",
          "Senape al miele",
          "Panna",
          "Limone",
          "Lime",
        ],
        "🧄 Aromi & Spezie": [
          "Aglio",
          "Prezzemolo",
          "Basilico",
          "Menta",
          "Erba cipollina",
          "Rosmarino",
          "Timo",
          "Salvia",
          "Zenzero fresco",
          "Peperoncino fresco",
          "Origano",
          "Paprika dolce",
          "Paprika affumicata",
          "Curry",
          "Cumino",
          "Curcuma",
          "Peperoncino secco",
          "Cannella",
          "Pepe",
        ],
        "🫙 Dispensa": [
          "Olive nere",
          "Olive verdi",
          "Olive taggiasche",
          "Capperi",
          "Pomodori secchi",
          "Semi di sesamo",
          "Semi di zucca",
          "Noci",
          "Mandorle",
          "Pistacchi",
          "Anacardi",
          "Pinoli",
        ],
      };


// Unica fonte di verità per il file principale ForkFolio.html.
window.FORKFOLIO_DATA = { STAPLES, INGREDIENTS, RECIPES, SHOP_CATS };
})();
